worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;

        root /var/www/html/wordpress;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        rewrite ^/wp-json/(.*)$ /index.php?rest_route=/$1 last;

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_param QUERY_STRING $query_string;
            fastcgi_param HTTP_AUTHORIZATION $http_authorization;
            fastcgi_param HTTP_X_SPRITZ_NOW_PLAYING_TOKEN $http_x_spritz_now_playing_token;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            expires max;
            log_not_found off;
        }

        location = /favicon.ico {
            log_not_found off;
            access_log off;
        }

        location = /robots.txt {
            log_not_found off;
            access_log off;
        }
    }
}
